### ISSUE TITLE
\r newlines

### ISSUE THREAD

**Issue by stasoid** [adyxax/zigfunge98#1]
Can you please clarify this situation: when zigfunge98 rejects standalone \r characters, is this a deliberate deviation from Funge-98 specification or not? [The spec says](https://github.com/catseye/Funge-98/blob/master/doc/funge98.markdown#funge-source-file-format) that \r "should, ideally, be recognized by the interpreter as an end-of-line marker". Official interpreter FBBI also [supports \r newlines](https://tio.run/##S0oszvj/PzU5I19BN09BRd3AMF3HIabIUV3BTiGNSz@/oEQ/KTWtNC89VdfSQj8pM08/LSkpUyHt/38A).

I am asking because in my program there are standalone \r chars and I cannot change that (because it is a polyglot and other languages require them). It's a shame I cannot use your interpreters with my program, these are some good Befunge-98 interpreters.

I don't even need that standalone \r be a newline. I just need that a program containing those not be rejected.

[Related.](https://github.com/adyxax/nimfunge98/issues/1)

If you don't want to deal with these issues, I can write a PR myself, but I need to know your opinion on this.

**Comment by adyxax** [comment]
Hi,

That is not intentional, I did not really test \r as a line ending character. It is weird that the mycology test suite does not fail on this behavior, maybe I trusted it too much!

Should be a very simple fix, I will look into this over the weekend.

**Comment by adyxax** [comment]
\r newlines should be handled properly now!

I would appreciate if you could please confirm it is all good for you too.

**Comment by stasoid** [comment]
Yes, it works for me. Thank you!

**Comment by adyxax** [comment]
Great to hear!

**Comment by adyxax** [comment]
I did not know about tio.run, what a great resource thank you!

**Comment by stasoid** [comment]
Indeed. Unfortunately, it stopped being updated a couple of years ago, which spawned alternatives like [ATO](https://ato.pxeger.com/run). But you cannot access other languages from bash on ATO.
